const cases = [
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
    {cases: 0 },
]

export default cases